run_name: # your own run anme # "debug" for debugging
train_path: #/define/your/path 
val_path: #/define/your/path 
ckpt_save_path: #/define/your/path 

pt_ckpt_path: null # (optional) path for pre-trained checkpoint
model_config: model/clip.yml 

device: cuda
num_epochs: 50 
early_stop_threshold: 5  
batch_size: 32  
lr: 1.0e-5 
optimizer: AdamW
warmup_steps: 0  
scheduler: reduceLR  # Scheduler type: reduceLR, linear, constant, etc
log_interval: 10
patience: 3
gnn_emb: eq_emb # leave it as eq_emb. in this paper, we exclusively used equiformer embedding
# chg_emb: False # False for not adding CHGNet embeddings
debug: False