run_name: # your own run name  
train_path: #/define/your/path 
val_path: #/define/your/path 
ckpt_save_path: #/define/your/path 

resume_path: null # checkpoint for resuming training
resume_config: null # config for resuming training

pt_ckpt_path: null # (optional) path for pre-trained checkpoint
model_config: model/clip.yml 

head: pooler
device: cuda
num_epochs: 50
early_stop_threshold: 4
batch_size: 32
lr: 1.0e-5
warmup_steps: 0
optimizer: AdamW # AdamW, gLLRD
scheduler: reduceLR
loss_fn: MSELoss
log_interval: 10
debug: False
